border:
  size: 1000
  shrink-phases:
    # phase 1
    -  size: 500      # size of border after 1st shrink
       time: 0        # after game enters BORDER_SHRINK state
       length: 450    # time it takes to shrink to this size in seconds
       # 450 seconds = 7.5 minutes

    # phase 2
    -  size: 100      # size of border after 2nd shrink
       time: 600      # time in seconds after previous shrink is done to start this shrink
       length: 900    # time it takes to shrink to this size
       # 900 seconds = 15 minutes

deathmatch:
  enabled: true
  time: 900 # time in seconds after border is DONE shrinking
  spawn: "" # location of deathmatch spectator spawn
  team-locations: [ ] # team locations for deathmatch

beacon:
  y-max: 319
  y-min: 20

lobby:
  spawn: ""
  y-min: -60 # teleport back after player goes below -60 y level

spectate-after-death: true

#allow teammates to hit eachother
friendly-fire: true

