"main": "${main}"
"name": "\${name}"
"version": "${pluginVersion}"
"api-version": "\${apiversion}"
"depend":
  - FastAsyncWorldEdit

#in alphabetical order
"authors":
  - "art_i_choked"
  - "babu"
  - "iMoltres"
  - "magicflakes"
  - "RuneixX"
