"main": "${main}"
"name": "${name}"
"version": "${pluginVersion}"
"api-version": "${apiversion}"
"depend":
  - FastAsyncWorldEdit

"authors":
  - "iMoltres"
  - "art_i_choked"
  - "babu"
  - "magicflakes"
  - "RuneixX"
