"main": "@main@"
"name": "@name@"
"version": "@version@"
"api-version": "@api-version@"
#in alphabetical order
depend:
  - FastAsyncWorldEdit
"authors":
  - "art_i_choked"
  - "babu"
  - "iMoltres"
  - "magicflakes"
  - "RuneixX"
